name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.5.0'

      - name: Check Node.js version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Check jest binary permissions
        run: ls -l node_modules/.bin/jest

      - name: Fix jest permissions
        run: chmod +x node_modules/.bin/jest

      - name: Run tests
        run: npm test